### ISSUE TITLE
MGF file errors in version 0.2.0+

### ISSUE THREAD

**Issue by chrishuges** [kevinkovalchik/RawQuant#11]
I am finding that the MGF file created in version 0.2.0 gives errors when working with most search engines. I assume the newer versions of RawQuant will as well, but I am not able to test this due to not being able to create MGFs because of the error I posted a couple of days ago.

I am able to create working MGFs from version 0.1.4.2. I am not sure what has changed between those versions?

**Comment by chrishuges** [comment]
I am able to make MGFs on Windows with 0.2.3. I will test these MGFs with a search and see what happens.

**Comment by kevinkovalchik** [comment]
I just got back from vacation. I'll look into this as soon as possible.

**Comment by kevinkovalchik** [comment]
I've checked all the search engines available in SearchCLI and they seem to do fine the v0.2.3 MGF file. I wasn't able to check Andromeda because I'm testing on a linux system.
