### ISSUE TITLE
File access issue with RawQuant v0.2.2 (QC) on win7

### ISSUE THREAD

**Issue by phegnal** [kevinkovalchik/RawQuant#12]
When run with the following parameters
python -m RawQuant qc -d D:\Data\RawQuantQC_data -q D:\Data\RawQuantQC_data\output

It fails with:
FileNotFoundError: File b’D:\\Data\\RawQuantQC_data\\output/latest_QC.csv’ does not exist.

It does seem to be expecting unix type directory separation by slash and not windows type backslash.

python -mRawQuant quant -r TMT11 -d D:\Data\RawQuantQC_data is running fine

**Comment by chrishuges** [comment]
I am not sure the -q flag is required. What happens if you just run -d?

**Comment by phegnal** [comment]
Then it fails because it has not been set 

C:\Users\Thermo>python -m RawQuant qc -d D:\Data\RawQuantQC_data
Traceback (most recent call last):
  File "C:\Users\Thermo\AppData\Local\Programs\Python\Python36\lib\runpy.py", li
ne 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Thermo\AppData\Local\Programs\Python\Python36\lib\runpy.py", li
ne 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Thermo\AppData\Local\Programs\Python\Python36\lib\site-packages
\RawQuant\__main__.py", line 891, in <module>
    quality_control.do_qc(qc_directory=args.qc_directory, path_to_file=args.rawf
ile, directory=args.directory)
  File "C:\Users\Thermo\AppData\Local\Programs\Python\Python36\lib\site-packages
\RawQuant\qc.py", line 46, in do_qc
    check_qc_directory(qc_directory)
  File "C:\Users\Thermo\AppData\Local\Programs\Python\Python36\lib\site-packages
\RawQuant\qc.py", line 13, in check_qc_directory
    if qc_directory[-3:] != '.qc':
TypeError: 'NoneType' object is not subscriptable

**Comment by chrishuges** [comment]
Yes ok. So based on this second error it seems you need to actually set the directory to something like 'output.qc'

For example:

```console
D:\chughes\rawQuant-QCtesting\RawQuant-qc_dev>python -m RawQuant qc -d D:\chughes\rawQuant-QCtesting\raw-files -q D:\chughes\rawQuant-QCtesting\raw-files\output.qc
Opening D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw and initializing

Data file: D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw
Instrument: Orbitrap Fusion
Experiment MS order: 2

D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting precursor scan numbers
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting MS1TrailerExtra
100%|███████████████████████████| 2622/2622 [00:00<00:00, 5786.28it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting MS2TrailerExtra
100%|█████████████████████████| 39992/39992 [00:04<00:00, 9337.97it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting MS1LabelData
100%|████████████████████████████| 2622/2622 [00:06<00:00, 395.95it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting MS1 retention times
100%|█████████████████████████████████████| 2622/2622 [00:00<?, ?it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting precursor peak data
100%|█████████████████████████| 39992/39992 [00:21<00:00, 1854.97it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Extracting MS2LabelData
100%|█████████████████████████| 39992/39992 [00:14<00:00, 2785.98it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw: Generating MS metrics file
Opening D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw and initializing

Data file: D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw
Instrument: Orbitrap Fusion
Experiment MS order: 2

Closing D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_1.raw
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting precursor scan numbers
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting MS1TrailerExtra
100%|███████████████████████████| 2587/2587 [00:00<00:00, 5589.05it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting MS2TrailerExtra
100%|█████████████████████████| 40349/40349 [00:04<00:00, 9094.11it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting MS1LabelData
100%|████████████████████████████| 2587/2587 [00:06<00:00, 378.73it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting MS1 retention times
100%|█████████████████████████| 2587/2587 [00:00<00:00, 368556.25it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting precursor peak data
100%|█████████████████████████| 40349/40349 [00:20<00:00, 1946.02it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Extracting MS2LabelData
100%|█████████████████████████| 40349/40349 [00:12<00:00, 3222.79it/s]
D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw: Generating MS metrics file
Closing D:\chughes\rawQuant-QCtesting\raw-files/ch_15Feb2018_SP3-MagReSyn-TMT6_hph_2.raw
```

**Comment by chrishuges** [comment]
I think Kevin is still actively coding on the QC part, so this isn't very well described in the command line help.

On a side note Kevin, the 'pre-existing files' seems to be working. If I add a file in after processing it just processes new files.

**Comment by phegnal** [comment]
Thanks. Yes that does the trick. 
Processing an existing file fine but does not seem to monitor for new files but stops after processing and so far the plots directory remains empty but I will figure that out.

**Comment by phegnal** [comment]
Thanks for the quick help!

**Comment by chrishuges** [comment]
Yes we have disabled the real-time monitoring at the moment. I can't remember how we left this Kevin...did we plan to have it operate this way? Or just have the user trigger it?

For plots yes, I don't think any plots have been designed yet. I think we were still figuring out how best to incorporate that, either through a GUI or an R Shiny app, or just an html output. Any suggestions are welcome!

**Comment by phegnal** [comment]
R shiny would likely be the best balance for ease of integration and quality of output. html should be very straight forward or just generate static plots in a directory and leave it to the user to display. 
You mentioned before it would generate a PDF (not a fan of) with plots so that's why I thought it was a bug that they are not there.

**Comment by chrishuges** [comment]
Maybe we can use [Bokeh](http://bokeh.pydata.org/en/latest/) for this Kevin? It seems to have the same functionality in Python as R Shiny, so would avoid having to cross over.

**Comment by chrishuges** [comment]
Will transfer this discussion elsewhere.

**Comment by kevinkovalchik** [comment]
Sure, we can use Bokeh for it.

Yes, the QC branch is still being worked on, so things are poorly described or not functional.

I found having it continuously monitor for new files was finicky so I opted to ditch that for now. If this would be an extremely desirable feature, I can work on it more in the future.
