### ISSUE TITLE
Error on Linux: pythonnet

### ISSUE THREAD

**Issue by antortjim** [kevinkovalchik/RawQuant#14]
Hi there!

Thanks for developing RawQuant. I feel like it's a really promising tool that will help fixing the "bottleneck" imposed by propietary formats like .RAW in proteomics.

I would like to report an issue I am experiencing trying to install RawQuant on Linux, originating from RawQuant dependency on [pythonnet](https://github.com/pythonnet/pythonnet).

This link leads to the Python traceback I am getting. [pythonnet_error.txt](https://github.com/kevinkovalchik/RawQuant/files/2195637/pythonnet_error.txt)

I think the error is due to pythonnet requiring some dependencies as well. They are listed [here](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX). I will post them here too:

To install on Linux some dependencies are required such as:

* Mono-complete (http://www.mono-project.com/docs/getting-started/install/linux/)
* clang (`sudo apt-get install clang`)
* glib (`sudo apt-get install libglib2.0-dev`)

Unfortunately, I don't have sudo access in my machine right now. I will update when I do!

Best regards

Antonio

**Comment by chrishuges** [comment]
Hi Antonio,

Yes this error is it looking for clang which you will need admin to install. Once you have installed those dependencies, RawQuant should load up fine for you. 

We are actively working on a C# version of RawQuant that will sidestep some of these dependency issues.

**Comment by antortjim** [comment]
Hi Chris,

Thank you for looking into this! 
I just tried on another Linux machine where I have sudo access. I made sure the 3 pythonnet dependencies  are available in my system (see log below), but still I cannot get it to work.

**Environment**

```
Pythonnet version: master and 2.3.0
Python version: 3.6.5
Pip version: 9.03 and 10.0.1
Operating System: Ubuntu 16.04 64 bits

mono --version

Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:48:32 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

ldd --version

ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

clang --version

clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```


I am trying to install pythonnet before RawQuant via 
1. `pip install pythonnet`
2. `pip install --egg pythonnet`
3. `pip install git+https://github.com/pythonnet/pythonnet -U --force`
 (2 is suggested in https://github.com/pythonnet/pythonnet/issues/562 and https://github.com/pythonnet/pythonnet/issues/555)

They all end with the same error. The full traceback, with and without the `--egg` flag is available in files below.

 ```
 subprocess.CalledProcessError: Command '['/home/antortjim/anaconda3/envs/python36/bin/python', 'tools/geninterop/geninterop.py', 'src/runtime/interop36m.cs']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/antortjim/anaconda3/envs/python36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ne_obuys/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-naeeah33/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/home/antortjim/anaconda3/envs/python36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ne_obuys/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-naeeah33/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-ne_obuys/

```

Thanks beforehand. Looking forward to get it to work on Linux!!

Best

Antonio

[pythonnet_egg_error.txt](https://github.com/kevinkovalchik/RawQuant/files/2196719/pythonnet_egg_error.txt)
[pythonnet_error.txt](https://github.com/kevinkovalchik/RawQuant/files/2196720/pythonnet_error.txt)

**Comment by antortjim** [comment]
Hi Chris

Just followed the steps on my default Python environment (previous was a conda environment).

```
python --version
Python 3.5.2
pip --version
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

* Downloaded the SSL certificates
```
wget https://curl.haxx.se/ca/cacert.pem
cert-sync --user ./cacert.pem #sync certificates
```

* Made sure to have complete mono
`sudo apt-get install mono-complete`
* Installed the pycparser package
`pip install pycparser #install pycparser package`

* Download pythonnet and install from zip
```
wget https://github.com/pythonnet/pythonnet/archive/master.zip
unzip master.zip
cd pythonnet-master
pip install . 
```
Remarkably... the install apparently works!
```
Processing /home/antortjim/MEGA/opt/pythonnet-master
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... done
  Stored in directory: /home/antortjim/.cache/pip/wheels/dc/ce/21/95a324c6b084a0ec093e195382aa9f04e0e57d00be487feebd
Successfully built pythonnet
Installing collected packages: pythonnet
  Found existing installation: pythonnet 2.4.0.dev0
    Uninstalling pythonnet-2.4.0.dev0:
      Successfully uninstalled pythonnet-2.4.0.dev0
Successfully installed pythonnet-2.4.0.dev0
```
but importing the module in an interactive session returns an error

Unfortunately I cannot install RawQuant because it requires Python >= 3.6.

Running the same commands in the conda environment above (Python 3.6.5) still gives the same error from before (see traceback at the end of the message).

I will post this in the pythonnet repo when I have more time to debug and test other ideas. In the meanwhile, I think it's useful to keep it here for others who might have similar issues :)

Thank you very much

Sincerely
Antonio

```
pip install --user .

Processing /home/antortjim/MEGA/opt/pythonnet-master
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /home/antortjim/anaconda3/envs/python36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-oe7ksrms/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-afch6a8q --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 4.6.2.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder '/tmp/pip-req-build-oe7ksrms/packages'
  Adding package 'NUnit.3.7.1' to folder '/tmp/pip-req-build-oe7ksrms/packages'
  Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-req-build-oe7ksrms/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-req-build-oe7ksrms/packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder '/tmp/pip-req-build-oe7ksrms/packages'
  Added package 'NUnit.3.7.1' to folder '/tmp/pip-req-build-oe7ksrms/packages'
  
  NuGet Config files used:
      /tmp/pip-req-build-oe7ksrms/NuGet.config
      /home/antortjim/.config/NuGet/NuGet.Config
  
  Feeds used:
      /home/antortjim/.nuget/packages/
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  clang: warning: /home/antortjim/anaconda3/envs/python36/include/python3.6m: 'linker' input unused
  Traceback (most recent call last):
    File "tools/geninterop/geninterop.py", line 292, in <module>
      sys.exit(main())
    File "tools/geninterop/geninterop.py", line 274, in main
      ast = parser.parse(python_h)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/pycparser/c_parser.py", line 152, in parse
      debug=debuglevel)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
      return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
      tok = call_errorfunc(self.errorfunc, errtoken, self)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
      r = errorfunc(token)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/pycparser/c_parser.py", line 1761, in p_error
      column=self.clex.find_tok_column(p)))
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/pycparser/plyparser.py", line 66, in _parse_error
      raise ParseError("%s: %s" % (coord, msg))
  pycparser.plyparser.ParseError: /usr/include/crypt.h:33:6: before: __THROW
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-oe7ksrms/setup.py", line 527, in <module>
      zip_safe=False,
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/setuptools/__init__.py", line 131, in setup
      return distutils.core.setup(**attrs)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-oe7ksrms/setup.py", line 475, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-req-build-oe7ksrms/setup.py", line 220, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "/home/antortjim/anaconda3/envs/python36/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/antortjim/anaconda3/envs/python36/bin/python', 'tools/geninterop/geninterop.py', 'src/runtime/interop36m.cs']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/antortjim/anaconda3/envs/python36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-oe7ksrms/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5mz391vi/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/home/antortjim/anaconda3/envs/python36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-oe7ksrms/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5mz391vi/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-oe7ksrms/
```

**Comment by kevinkovalchik** [comment]
Hi Antonio,

Python 3.6 is required simply because we haven't tested any earlier versions. We had some troubles with other versions when we were using MSFilerReader, but we haven't really tested different versions since moving to RawFileReader. It might work fine with 3.5. You can try this:
1. Download the RawQuant master branch and unpack it to a directory
2. In the setup.py file, change `python_requires='>=3.6'` to `python_requires='>=3.5'`
3. Install RawQuant with `$ pip install .` from the directory containing setup.py.

Kevin

**Comment by antortjim** [comment]
Hi Kevin

Indeed, **it works on Python 3.5.2**!!! :tada: 
I tried the following commands:

From the tutorial:
```
python -m RawQuant parse -f ch_29Sept2017_eColi-31907_TMT11_MS2_1.raw -o 1 2 -mgf -mtx
```

Using [one of the raw files](https://www.ebi.ac.uk/pride/data/archive/2014/09/PXD000279/20071004_CL_Orbi2_XIC_Hela60_Ecoli30_Offgel_red_Frac_24_01.RAW) in the [MaxLFQ dataset](https://www.ebi.ac.uk/pride/archive/projects/PXD000279):
```
python -m RawQuant parse -f 20071004_CL_Orbi2_XIC_Hela60_Ecoli30_Offgel_red_Frac_24_01.RAW -o 1 2 -mgf -mtx
```
Both run **without errors** and return the expected files:

* metrics.txt 
* MS1ParseData.txt
* MS2ParseData.txt
* MGF

The fact that RawQuant can extract MGF files and PrecursorMaxIntensity & PrecursorArea **in Linux** is pretty amazing!! Thank you for that!

- Is this PrecursorMaxIntensity analogous to the Apex Intensity produced by [moFF](https://github.com/compomics/moFF)?
- If that's the case, I understand that either of them could be used to perform label-free quantification with packages like MSnBase or MSqRob. Am I correct?

Thank you so much for your help and your fast input. I hope others facing the same problem find this thread useful. In any case, building a Docker image could make deployment easier. I wouldn't mind contributing to the project in this way :)

Best regards

Antonio

**Comment by kevinkovalchik** [comment]
I'm not familiar with the exact processing going on in moFF, so I can't say if ours is analogous. But here's what I can tell you about what we are doing:

We are not doing any peak fitting. The max intensity value is pulled directly from the MS1 data of the highest intensity scan for the eluting peak.
For peak area, we are using a trapezoidal "integration", so basically we are connecting the dots with straight lines and then reporting the area under the lines. The dots being the time-intensity coordinates of that peak in each scan. Speaking of time-intensity, we are also not doing any stretching or alignment of the chromatograms.

A docker image sounds interesting. Chris and I will talk about it. It is not something I am experienced in, so if we go that route some assistance would be appreciated. :)

Kevin

**Comment by antortjim** [comment]
moFF performs MBR and Apex intensity extraction. I think the latter is analogous to the max intensity, because if I understood correctly, "pulling a value directly from MS1 data of the highest intensity scan for the eluting peak" means for each peak cluster on the m/z and RT place, you find its summit, right? Please correct me otherwise. I think it would be great if both tools talked to each other.

Sure! I would be happy to give it a try. Not now as I am currently finishing writing my Master Thesis :coffee: :computer: :dizzy_face: (on proteomics as you might have guessed). But I will soon be done. Just let me know if that's the case

Best

Antonio

PS I will close the issue as I got it to work. Maybe we should open another one for the comparison with moFF?

**Comment by chrishuges** [comment]
Just re-opening this issue to comment quickly on the moFF thing. As you mentioned, moFF operates in two different ways:

1. Apex - it makes an XIC for a given mass and extracts the apex intensity (from what I can tell no real curve fitting is done here - look at Supplementary Figure 2 in the [moFF manuscript](https://www.nature.com/articles/nmeth.4075#s1)). 

2. MBR - uses a list of features from one file to look for features that were otherwise not identified in another file using RT and mass information. This also uses the Apex method to get the intensity (no curve fitting). 

So, the RawQuant values should align pretty much exactly with what moFF is doing independent of the moFF method used. The main difference between the tools is that moFF is operating on peptide results whereas RawQuant returning values for all features in the raw file. I am not sure if moFF would add anything to what RawQuant is already doing. 

Chris

**Comment by antortjim** [comment]
Thanks for your message Chris.

I see, so intensity extraction-wise, I think moFF doesn't add to RawQuant, it just operates on peptide results. But the MBR module is something on its own.
I am not an expert, but I think moFF could benefit from the apparently (haven't had time to go deep into it) pretty comprehensive parsing done by RawQuant, and RawQuant from the MBR module in moFF.

Antonio

**Comment by kevinkovalchik** [comment]
Yeah, the MBR module is interesting. We work with labeled quantification a lot, so finding features in a given file that were not identified isn't something we have thought about much. It wouldn't add any value to labeled quant except to say that feature was found in at least one of the multiplexed samples.

Having said that, this feature wouldn't be too hard to add to RQ if people working with unlabeled quant would appreciate it. Though I'm not sure there would be any advantage to doing it pre-identification as opposed to post-identification. We would probably end up cross-referencing lots of features that don't get ID'd anyway.

**Comment by chrishuges** [comment]
I think there would be a definite disadvantage to doing it pre-identification as it would require detecting and quantifying every feature found in the MS1 scans, whereas now we just analyze those that were selected for MS2. There are also issues related to batching files if you do it pre-identification.

I am not sure it is actually worth doing anything here. We would simply be re-writing the code for moFF to replicate the exact functionality of this existing tool. I don't see the point.

**Comment by kevinkovalchik** [comment]
In general, I agree. I wan't thinking of correlating every MS1 feature, but rather just those picked for ms2. So you might have the same feature in two files, but it was only picked for ms2 in one of those files. Maybe I misinterpreted what MBR is doing.
Anyway, I agree people would be better served by using a tool that already does this for identifications. There's no reason for us to do it.
