### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by markmipt** [kevinkovalchik/RawQuant#8]
Link to the "installation and tutorial file" on the main page refer to an old file (*Mar2018.md) instead of new *May file.

**Comment by chrishuges** [comment]
Now that the linux version is merged with the master branch, we should update this walkthrough file. I will work on this today.

**Comment by kevinkovalchik** [comment]
Oops. Thanks for the heads up. I did some updates on the walk-through and updated the filename, but forgot to change the link.

**Comment by kevinkovalchik** [comment]
The link is working now.
Chris, if you get a chance today go ahead and check over the new instructions to see if you see anything missing.
