### ISSUE TITLE
Adding information to the metrics file

### ISSUE THREAD

**Issue by chrishuges** [kevinkovalchik/RawQuant#9]
Would be nice if the MS2 detector was output to the MGF file. Right now we just put instrument, which is great, but adding the detector would be good as well.

**Comment by kevinkovalchik** [comment]
Sure, this can be added. Will work on it.

**Comment by kevinkovalchik** [comment]
I added analyzer types for each MS order to the metrics file.

example:
```
Raw file:	Lumos_data.raw
Instrument:	Orbitrap Fusion Lumos
MS order:	3
MS1 analyzer type:	FTMS
MS2 analyzer type:	ITMS
MS3 analyzer type:	FTMS
Total analysis time (min):	45.0042
⋮
```
